// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3akd4RQ7dG7Cg-yC19GfKCVPEg0CfpXY',
    appId: '1:496731825025:web:12fbbacfc7f2fdc5ce3e80',
    messagingSenderId: '496731825025',
    projectId: 'shop-app-ecommerce',
    authDomain: 'shop-app-ecommerce.firebaseapp.com',
    storageBucket: 'shop-app-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_9j3D5mZgS9MwRbc0HpHOkyyNirVDGt0',
    appId: '1:496731825025:android:0baebf565edbad26ce3e80',
    messagingSenderId: '496731825025',
    projectId: 'shop-app-ecommerce',
    storageBucket: 'shop-app-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ8IohklHnON9ex6_yPOY8i-4Ru30H_i8',
    appId: '1:496731825025:ios:5a24f7732f3723b9ce3e80',
    messagingSenderId: '496731825025',
    projectId: 'shop-app-ecommerce',
    storageBucket: 'shop-app-ecommerce.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ8IohklHnON9ex6_yPOY8i-4Ru30H_i8',
    appId: '1:496731825025:ios:5a24f7732f3723b9ce3e80',
    messagingSenderId: '496731825025',
    projectId: 'shop-app-ecommerce',
    storageBucket: 'shop-app-ecommerce.appspot.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3akd4RQ7dG7Cg-yC19GfKCVPEg0CfpXY',
    appId: '1:496731825025:web:b460089461874ba4ce3e80',
    messagingSenderId: '496731825025',
    projectId: 'shop-app-ecommerce',
    authDomain: 'shop-app-ecommerce.firebaseapp.com',
    storageBucket: 'shop-app-ecommerce.appspot.com',
  );
}
